-- Contact posting accounts from the Sage lists: Vendor List.xlsx, Customer List 09272026.pdf
-- Generated by tools/sage-lists-sql.py. Run in the Supabase SQL editor AFTER migration 024.
-- The org is the first on file (the shop's own); the editor runs as postgres, not a user.

-- 1. Vendors: expense account, 1099 type, and tax id / vendor id where blank.
update contacts c set
  expense_account = v.acct,
  ten99 = v.ten99,
  tax_id = case when coalesce(btrim(c.tax_id), '') = '' then v.tax else c.tax_id end,
  code   = case when coalesce(btrim(c.code), '') = '' then v.vid else c.code end
from (values
  ('4tccoropration', '6700', '', '35-2033958', '4TC'),
  ('aircenterinc', '6750', '', '', 'Air Center'),
  ('arkenstoneenterprises', '6700', 'misc', '20-0088428', 'Arkenstone'),
  ('hhbarnumcompany', '6750', '', '', 'Barnum'),
  ('3bsengineering', '6700', 'misc', '46-1990198', 'BBB'),
  ('beaconcovemarina', '6300', '', '', 'BCM'),
  ('thebenefitadvantage', '6050', '', '', 'Benefit'),
  ('bernadettesfaithinaction', '6610', '', '', 'Bernadette'),
  ('centurycharities', '6610', '', '', 'Century Charities'),
  ('haeckcontrolsllc', '6700', 'misc', '309-70-5209', 'DH'),
  ('doxsielawfirm', '6560', 'misc', '47-3049078', 'DOXSIE'),
  ('elishabrockert', '6700', 'misc', '380-25-4887', 'Eli'),
  ('fivesdyagcorp', '6700', '', '', 'Fives'),
  ('gvironworks', '6750', '', '', 'G&V'),
  ('ifmefectorinc', '6750', '', '', 'IFM'),
  ('invesco', '2390', '', '', 'Invesco'),
  ('jssystemsintegrators', '6700', 'misc', '73-1691166', 'J&S'),
  ('johnjakuszanek', '6700', 'misc', '378567659', 'JohnJak'),
  ('frankkapral', '6700', 'misc', '368-78-6731', 'Kapral'),
  ('lyndascadservice', '6700', 'misc', '32-0108363', 'LB'),
  ('lakegogebicchamberofcommerce', '6600', '', '', 'LGCC'),
  ('jeffreylsmith', '6700', 'misc', '379-94-8522', 'LogixWise'),
  ('mauroengineering', '6700', '', '', 'Mauro'),
  ('jackmccainplumbingheatinginc', '6750', '', '', 'McCain'),
  ('mcdonaldhopkins', '6560', '', '', 'MH'),
  ('stateofmichigan', '6200', '', '', 'MI'),
  ('stateofmichiganoc', '6250', '', '', 'MI-OC'),
  ('terryminnis', '6700', 'misc', '372-64-4183', 'Minnis'),
  ('johnmurphy', '6610', '', '', 'Murphy'),
  ('nationalpencollc', '6600', '', '', 'Nat Pen'),
  ('nationwidelifeandannuityinsurance', '6950', '', '', 'Nationwide'),
  ('dydenosmundsontechnologiesllc', '6700', 'misc', '', 'PO'),
  ('powerhousegenerators', '6750', '', '', 'Powerhouse'),
  ('romeohighschool', '6600', '', '', 'Romeo'),
  ('charlesschwab', '2390', '', '', 'Schwab'),
  ('nealsinacola', '6700', 'misc', '377-64-4858', 'Sinacola'),
  ('sparktalentacquisition', '6700', '', '', 'Spark'),
  ('tailoredcontrolsdesignllc', '6700', 'misc', '', 'Tailored Controls'),
  ('testwellelectronicsltd', '6750', '', '', 'TestWell'),
  ('tomjakuszanek', '6000', '', '', 'TJ'),
  ('uline', '6750', '', '', 'ULine'),
  ('unitedstatestreasury', '6250', '', '', 'US Treasury'),
  ('unlimitedtechnologies', '6700', 'misc', '', 'UT'),
  ('venuscontrols', '6750', '', '', 'VC'),
  ('aaronvleck', '6700', 'misc', '367-78-4304', 'Vleck'),
  ('watkinslakelandsimprovementassoc', '6600', '', '', 'W.L.I.A'),
  ('rhwittinc', '6700', 'misc', '', 'WItt'),
  ('xaticautomatizaion', '6700', '', '', 'Xatic'),
  ('xlmcapitalmanagement', '6050', '', '', 'XLM'),
  ('yasproelectronics', '6750', '', '', 'Yaspro'),
  ('christianeyasso', '6700', 'misc', '368826916', 'Yasso')
) as v(name_key, acct, ten99, tax, vid)
where c.type = 'vendor'
  and c.org_id = (select id from orgs order by created_at limit 1)
  and regexp_replace(lower(c.name), '[^a-z0-9]', '', 'g') = v.name_key;

-- 2. Customers: sales account.
update contacts c set sales_account = v.acct
from (values
  ('automatedcontrolsystem', '4000'),
  ('alliedindustrialsolutionas', '4000'),
  ('argusassociates', '4000'),
  ('automatedsolutions', '4000'),
  ('bulldogfactorydesign', '4000'),
  ('bearindustrialgroup', '4000'),
  ('briggs', '4000'),
  ('comtechinternationaldesi', '4000'),
  ('elitelineservices', '4000'),
  ('deluxetechnologies', '4000'),
  ('deversitechinc', '4000'),
  ('domtarindustries', '4000'),
  ('internationalrobotsupport', '4000'),
  ('fisherdynamics', '4000'),
  ('gableindustries', '4000'),
  ('hyymould', '4000'),
  ('integratedsystemsdesign', '4000'),
  ('jvisusa', '4000'),
  ('maycointernationalllc', '4000'),
  ('motorcityelectrictechnol', '4000'),
  ('mino', '4000'),
  ('perceptroninc', '4000'),
  ('praettoolandengineering', '4000'),
  ('prefixcorporation', '4000'),
  ('rockwellautomation', '4000'),
  ('scottindustries', '4000'),
  ('truetechnologiesandmf', '4000'),
  ('venuscontrols', '4000'),
  ('ventureglobalengineering', '4000'),
  ('lwindustrialelectronics', '4000'),
  ('xpsautomation', '4000'),
  ('ziionroboticscontrolin', '4000')
) as v(name_key, acct)
where c.type = 'customer'
  and c.org_id = (select id from orgs order by created_at limit 1)
  and regexp_replace(lower(c.name), '[^a-z0-9]', '', 'g') = v.name_key;

-- 3. Review: contacts the lists did not name (set their account by hand).
select type, name, coalesce(nullif(sales_account, ''), nullif(expense_account, ''), '(none)') as account
from contacts
where org_id = (select id from orgs order by created_at limit 1)
  and ((type = 'vendor' and coalesce(expense_account, '') = '') or (type = 'customer' and coalesce(sales_account, '') = ''))
order by type, name;
