-- Sales-order reconciliation generated from: Sales Order Report 09122026.pdf
-- Generated by tools/so-report-sql.py. Run in the Supabase SQL editor.
-- Sage is the book of record: PO numbers, invoiced/open lines and SO status
-- below are brought into line with the report. Change the final COMMIT to
-- ROLLBACK to dry-run; the closing SELECT shows what would change either way.
begin;

create temp table so_report (so_number text, po_number text, pos int, line_desc text, shipped numeric, remaining numeric) on commit drop;
insert into so_report (so_number, po_number, pos, line_desc, shipped, remaining) values
  ('TMJ882', '4724-F1', 0, '4724-F1 Initial PO', 1, 0),
  ('TMJ882', '4724-F1', 1, '4724-F1 Engineering Com', 1, 0),
  ('TMJ882', '4724-F1', 2, '4724-F1 Panel Build Com', 1, 0),
  ('TMJ882', '4724-F1', 3, '4724-F1 Field Wire Compl', 0, 1),
  ('TMJ882', '4724-F1', 4, '4724-F1 Final Documenta', 0, 1),
  ('TMJ883', '4724-F2', 0, '4724-F2 Initial PO', 1, 0),
  ('TMJ883', '4724-F2', 1, '4724-F2 Engineering Com', 1, 0),
  ('TMJ883', '4724-F2', 2, '4724-F2 Panel Build Com', 1, 0),
  ('TMJ883', '4724-F2', 3, '4724-F2 Field Wire Compl', 0, 1),
  ('TMJ883', '4724-F2', 4, '4724-F2 Final Documenta', 0, 1),
  ('TMJ884', '4724-F3', 0, '4724-F3 Initial PO', 1, 0),
  ('TMJ884', '4724-F3', 1, '4724-F3 Engineering Com', 1, 0),
  ('TMJ884', '4724-F3', 2, '4724-F3 Panel Build Com', 1, 0),
  ('TMJ884', '4724-F3', 3, '4724-F3 Field Wire Compl', 0, 1),
  ('TMJ884', '4724-F3', 4, '4724-F3 Final Documenta', 0, 1),
  ('TMJ886', '4740LF', 0, '4740LF Initial PO', 1, 0),
  ('TMJ886', '4740LF', 1, '4740LF Design Complete', 1, 0),
  ('TMJ886', '4740LF', 2, '4740LF Panel Build Comp', 1, 0),
  ('TMJ886', '4740LF', 3, '4740LF Field Wire Compl', 1, 0),
  ('TMJ886', '4740LF', 4, '4740LF Final Documentati', 0, 1),
  ('TMJ887', '4740RF', 0, '4740RF Initial PO', 1, 0),
  ('TMJ887', '4740RF', 1, '4740RF Design Complete', 1, 0),
  ('TMJ887', '4740RF', 2, '4740RF Panel Build Com', 1, 0),
  ('TMJ887', '4740RF', 3, '4740RF Field Wire Compl', 1, 0),
  ('TMJ887', '4740RF', 4, '4740RF Final Documentat', 0, 1),
  ('TMJ888', '4737F2', 0, '4737F2 Initial PO', 1, 0),
  ('TMJ888', '4737F2', 1, '4737F2 Engineering Com', 1, 0),
  ('TMJ888', '4737F2', 2, '4737F2 Panel Build Comp', 1, 0),
  ('TMJ888', '4737F2', 3, '4737F2 Field Wire Compl', 1, 0),
  ('TMJ888', '4737F2', 4, '4737F2 Final Documentati', 0, 1),
  ('TMJ889', '4737F1', 0, '4737F1 Initial PO', 1, 0),
  ('TMJ889', '4737F1', 1, '4737F1 Engineering Com', 1, 0),
  ('TMJ889', '4737F1', 2, '4737F1 Panel Build Comp', 1, 0),
  ('TMJ889', '4737F1', 3, '4737F1 Field Wire Compl', 1, 0),
  ('TMJ889', '4737F1', 4, '4737F1 Final Documentati', 0, 1),
  ('TMJ890', '4743RF', 0, '4743RF Initial PO', 1, 0),
  ('TMJ890', '4743RF', 1, '4743RF Engineering Com', 1, 0),
  ('TMJ890', '4743RF', 2, '4743RF Panel Build Com', 1, 0),
  ('TMJ890', '4743RF', 3, '4743RF Field Wire Compl', 0, 1),
  ('TMJ890', '4743RF', 4, '4743RF Final Documentat', 0, 1),
  ('TMJ891', '4743LF', 0, '4743LF Initial PO', 1, 0),
  ('TMJ891', '4743LF', 1, '4743LF Engineering Com', 1, 0),
  ('TMJ891', '4743LF', 2, '4743LF Panel Build Comp', 1, 0),
  ('TMJ891', '4743LF', 3, '4743LF Field Wire Compl', 0, 1),
  ('TMJ891', '4743LF', 4, '4743LF Final Documentati', 0, 1),
  ('TMJ892', '2076', 0, '2076 Initial PO', 1, 0),
  ('TMJ892', '2076', 1, '2076 Engineering Comple', 1, 0),
  ('TMJ892', '2076', 2, '2743F Panel Build Compl', 1, 0),
  ('TMJ892', '2076', 3, '2076 Field Wire Complete', 1, 0),
  ('TMJ892', '2076', 4, '2076 Final Documentation', 0, 1),
  ('TMJ901', '4763', 0, '4763 Initial PO', 1, 0),
  ('TMJ901', '4763', 1, '4763 Engineering Comple', 0, 1),
  ('TMJ901', '4763', 2, '4763 Panel Build Complet', 0, 1),
  ('TMJ901', '4763', 3, '4763 Field Wire Complete', 0, 1),
  ('TMJ901', '4763', 4, '4763 Final Documentation', 0, 1),
  ('TMJ902', '4764', 0, '4764 Initial PO', 1, 0),
  ('TMJ902', '4764', 1, '4764 Engineering Comple', 0, 1),
  ('TMJ902', '4764', 2, '4764 Panel Build Complet', 0, 1),
  ('TMJ902', '4764', 3, '4764 Field Wire Complete', 0, 1),
  ('TMJ902', '4764', 4, '4764 Final Documentation', 0, 1),
  ('TMJ903', '4766', 0, '4766 Initial PO', 1, 0),
  ('TMJ903', '4766', 1, '4766 Engineering Comple', 0, 1),
  ('TMJ903', '4766', 2, '4766 Panel Build Complet', 0, 1),
  ('TMJ903', '4766', 3, '4766 Field Wire Complete', 0, 1),
  ('TMJ903', '4766', 4, '4766 Final Documentation', 0, 1),
  ('TMJ904', '4768', 0, '4768 Initial PO', 1, 0),
  ('TMJ904', '4768', 1, '4768 Engineering Comple', 0, 1),
  ('TMJ904', '4768', 2, '4768 Panel Build Complet', 0, 1),
  ('TMJ904', '4768', 3, '4768 Field Wire Complete', 0, 1),
  ('TMJ904', '4768', 4, '4768 Final Documentation', 0, 1),
  ('TMJ905', '4771', 0, '4771 Initial PO', 1, 0),
  ('TMJ905', '4771', 1, '4771 Engineering Comple', 0, 1),
  ('TMJ905', '4771', 2, '4771 Panel Build Complet', 0, 1),
  ('TMJ905', '4771', 3, '4771 Field Wire Complete', 0, 1),
  ('TMJ905', '4771', 4, '4771 Final Documentation', 0, 1),
  ('TMJ906', '4775', 0, '4775 Initial PO', 1, 0),
  ('TMJ906', '4775', 1, '4775 Engineering Comple', 0, 1),
  ('TMJ906', '4775', 2, '4775 Panel Build Complet', 0, 1),
  ('TMJ906', '4775', 3, '4775 Field Wire Complete', 0, 1),
  ('TMJ906', '4775', 4, '4775 Final Documentation', 0, 1),
  ('TMJ907', '4784', 0, '4784 Initial PO', 1, 0),
  ('TMJ907', '4784', 1, '4784 Engineering Comple', 0, 1),
  ('TMJ907', '4784', 2, '4784 Panel Build Complet', 0, 1),
  ('TMJ907', '4784', 3, '4784 Field Wire Complete', 0, 1),
  ('TMJ907', '4784', 4, '4784 Final Documentation', 0, 1),
  ('TMJ908', '4792', 0, '4792 Initial PO', 1, 0),
  ('TMJ908', '4792', 1, '4792 Engineering Comple', 0, 1),
  ('TMJ908', '4792', 2, '4792 Panel Build Complet', 0, 1),
  ('TMJ908', '4792', 3, '4792 Field Wire Complete', 0, 1),
  ('TMJ908', '4792', 4, '4792 Final Documentation', 0, 1),
  ('TMJ909', '4797', 0, '4797 Initial PO', 1, 0),
  ('TMJ909', '4797', 1, '4797 Engineering Comple', 0, 1),
  ('TMJ909', '4797', 2, '4797 Panel Build Complet', 0, 1),
  ('TMJ909', '4797', 3, '4797 Field Wire Complete', 0, 1),
  ('TMJ909', '4797', 4, '4797 Final Documentation', 0, 1),
  ('TMJ910', '4799', 0, '4799 Initial PO', 1, 0),
  ('TMJ910', '4799', 1, '4799 Engineering Comple', 0, 1),
  ('TMJ910', '4799', 2, '4799 Panel Build Complet', 0, 1),
  ('TMJ910', '4799', 3, '4799 Field Wire Complete', 0, 1),
  ('TMJ910', '4799', 4, '4799 Final Documentation', 0, 1),
  ('TMJ911', '4801', 0, '4801 Initial PO', 1, 0),
  ('TMJ911', '4801', 1, '4801 Engineering Comple', 0, 1),
  ('TMJ911', '4801', 2, '4801 Panel Build Complet', 0, 1),
  ('TMJ911', '4801', 3, '4801 Field Wire Complete', 0, 1),
  ('TMJ911', '4801', 4, '4801 Final Documentation', 0, 1),
  ('TMJ912', '4802', 0, '4802 Initial PO', 1, 0),
  ('TMJ912', '4802', 1, '4802 Engineering Comple', 0, 1),
  ('TMJ912', '4802', 2, '4802 Panel Build Complet', 0, 1),
  ('TMJ912', '4802', 3, '4802 Field Wire Complete', 0, 1),
  ('TMJ912', '4802', 4, '4802 Final Documentation', 0, 1);

-- text normaliser: case-, space- and punctuation-insensitive
create or replace function pg_temp.norm(t text) returns text language sql immutable as
$$ select regexp_replace(lower(coalesce(t, '')), '[^a-z0-9]', '', 'g') $$;

-- Ledger's lines for the sales orders on the report, with their position.
create temp table so_lines on commit drop as
select li.id, li.sales_order_id, s.number as so_number, li.description, li.invoiced, li.closed, li.invoice_id,
       row_number() over (partition by li.sales_order_id order by li.sort, li.created_at) - 1 as pos
from sales_order_line_items li
join sales_orders s on s.id = li.sales_order_id
where s.number in (select distinct so_number from so_report);

-- 1. Match each report line to a Ledger line: shortened description as a
--    prefix of the full one (position breaks a tie), else the same position.
create temp table so_match on commit drop as
select distinct on (r.so_number, r.pos)
       r.so_number, r.pos, r.line_desc, r.shipped, r.remaining, l.id as line_id, l.sales_order_id, l.description,
       l.invoiced as was_invoiced, l.closed as was_closed, l.invoice_id as old_invoice_id
from so_report r
left join so_lines l on l.so_number = r.so_number
  and pg_temp.norm(l.description) like pg_temp.norm(r.line_desc) || '%'
order by r.so_number, r.pos, (l.pos = r.pos) desc, l.pos;

update so_match m set line_id = l.id, sales_order_id = l.sales_order_id, description = l.description,
       was_invoiced = l.invoiced, was_closed = l.closed, old_invoice_id = l.invoice_id
from so_lines l
where m.line_id is null and l.so_number = m.so_number and l.pos = m.pos
  and l.id not in (select line_id from so_match where line_id is not null);

-- 2. Fill a blank PO number from the job number on the report.
update sales_orders s set po_number = r.po_number
from (select distinct so_number, po_number from so_report where po_number <> '') r
where s.number = r.so_number and coalesce(btrim(s.po_number), '') = '';

-- 3. Lines Sage has shipped: invoiced, not closed, linked to the invoice that
--    billed them (same sales order, same line text; earliest wins).
create temp table inv_match on commit drop as
select distinct on (m.line_id) m.line_id, i.id as invoice_id, i.number as invoice_number
from so_match m
join invoices i on i.sales_order_id = m.sales_order_id
join invoice_line_items il on il.invoice_id = i.id and pg_temp.norm(il.description) = pg_temp.norm(m.description)
where m.line_id is not null and m.shipped > 0
order by m.line_id, i.date, i.created_at;

update sales_order_line_items li
set invoiced = true, closed = false, invoice_id = coalesce(im.invoice_id, li.invoice_id)
from so_match m left join inv_match im on im.line_id = m.line_id
where li.id = m.line_id and m.shipped > 0;

-- 4. Lines Sage still has remaining: open again, so they are available to bill.
update sales_order_line_items li
set invoiced = false, closed = false, invoice_id = null
from so_match m
where li.id = m.line_id and m.shipped = 0 and m.remaining > 0;

-- 5. Recompute each sales order's status from its lines.
update sales_orders s
set status = case when agg.open_lines = 0 then 'invoiced' else 'open' end,
    invoice_id = case when agg.open_lines = 0 then coalesce(s.invoice_id, agg.last_invoice) else null end
from (
  select li.sales_order_id,
         count(*) filter (where not li.invoiced and not li.closed) as open_lines,
         max(li.invoice_id::text)::uuid as last_invoice
  from sales_order_line_items li
  where li.sales_order_id in (select distinct sales_order_id from so_lines)
  group by li.sales_order_id
) agg
where s.id = agg.sales_order_id;

-- 6. Review: one row per report line, what it was, what it is now.
select m.so_number, s.po_number, s.status as so_status, m.pos, m.line_desc as sage_line,
       case when m.shipped > 0 then 'invoiced' else 'open' end as sage_says,
       m.description as ledger_line,
       (case when m.was_invoiced then 'invoiced' when m.was_closed then 'closed' else 'open' end) as was,
       (case when li.invoiced then 'invoiced' when li.closed then 'closed' else 'open' end) as now,
       im.invoice_number as linked_invoice,
       case
         when m.line_id is null then 'NO LEDGER LINE MATCHED'
         when m.shipped > 0 and li.invoice_id is null then 'invoiced in Sage, no Ledger invoice found'
         when m.shipped = 0 and m.old_invoice_id is not null then 'unlinked invoice ' || coalesce((select number from invoices where id = m.old_invoice_id), m.old_invoice_id::text)
         when m.was_closed and li.invoiced then 'was closed by hand: marked invoiced'
         when m.was_closed and not li.closed then 'reopened'
         when not m.was_invoiced and li.invoiced then 'marked invoiced'
         else ''
       end as note
from so_match m
left join sales_orders s on s.number = m.so_number
left join sales_order_line_items li on li.id = m.line_id
left join inv_match im on im.line_id = m.line_id
order by m.so_number, m.pos;

commit;
