-- Sales-order reconciliation generated from: Sales Order Report 09122026.pdf
-- Generated by tools/so-report-sql.py. Run in the Supabase SQL editor.
-- Sage is the book of record: PO numbers, invoiced/open lines and SO status
-- are brought into line with the report. One statement, so it is all-or-nothing.
with report(so_number, po_number, pos, line_desc, shipped, remaining) as (values
  ('TMJ882', '4724-F1', 0, '4724-F1 Initial PO', 1, 0),
  ('TMJ882', '4724-F1', 1, '4724-F1 Engineering Com', 1, 0),
  ('TMJ882', '4724-F1', 2, '4724-F1 Panel Build Com', 1, 0),
  ('TMJ882', '4724-F1', 3, '4724-F1 Field Wire Compl', 0, 1),
  ('TMJ882', '4724-F1', 4, '4724-F1 Final Documenta', 0, 1),
  ('TMJ883', '4724-F2', 0, '4724-F2 Initial PO', 1, 0),
  ('TMJ883', '4724-F2', 1, '4724-F2 Engineering Com', 1, 0),
  ('TMJ883', '4724-F2', 2, '4724-F2 Panel Build Com', 1, 0),
  ('TMJ883', '4724-F2', 3, '4724-F2 Field Wire Compl', 0, 1),
  ('TMJ883', '4724-F2', 4, '4724-F2 Final Documenta', 0, 1),
  ('TMJ884', '4724-F3', 0, '4724-F3 Initial PO', 1, 0),
  ('TMJ884', '4724-F3', 1, '4724-F3 Engineering Com', 1, 0),
  ('TMJ884', '4724-F3', 2, '4724-F3 Panel Build Com', 1, 0),
  ('TMJ884', '4724-F3', 3, '4724-F3 Field Wire Compl', 0, 1),
  ('TMJ884', '4724-F3', 4, '4724-F3 Final Documenta', 0, 1),
  ('TMJ886', '4740LF', 0, '4740LF Initial PO', 1, 0),
  ('TMJ886', '4740LF', 1, '4740LF Design Complete', 1, 0),
  ('TMJ886', '4740LF', 2, '4740LF Panel Build Comp', 1, 0),
  ('TMJ886', '4740LF', 3, '4740LF Field Wire Compl', 1, 0),
  ('TMJ886', '4740LF', 4, '4740LF Final Documentati', 0, 1),
  ('TMJ887', '4740RF', 0, '4740RF Initial PO', 1, 0),
  ('TMJ887', '4740RF', 1, '4740RF Design Complete', 1, 0),
  ('TMJ887', '4740RF', 2, '4740RF Panel Build Com', 1, 0),
  ('TMJ887', '4740RF', 3, '4740RF Field Wire Compl', 1, 0),
  ('TMJ887', '4740RF', 4, '4740RF Final Documentat', 0, 1),
  ('TMJ888', '4737F2', 0, '4737F2 Initial PO', 1, 0),
  ('TMJ888', '4737F2', 1, '4737F2 Engineering Com', 1, 0),
  ('TMJ888', '4737F2', 2, '4737F2 Panel Build Comp', 1, 0),
  ('TMJ888', '4737F2', 3, '4737F2 Field Wire Compl', 1, 0),
  ('TMJ888', '4737F2', 4, '4737F2 Final Documentati', 0, 1),
  ('TMJ889', '4737F1', 0, '4737F1 Initial PO', 1, 0),
  ('TMJ889', '4737F1', 1, '4737F1 Engineering Com', 1, 0),
  ('TMJ889', '4737F1', 2, '4737F1 Panel Build Comp', 1, 0),
  ('TMJ889', '4737F1', 3, '4737F1 Field Wire Compl', 1, 0),
  ('TMJ889', '4737F1', 4, '4737F1 Final Documentati', 0, 1),
  ('TMJ890', '4743RF', 0, '4743RF Initial PO', 1, 0),
  ('TMJ890', '4743RF', 1, '4743RF Engineering Com', 1, 0),
  ('TMJ890', '4743RF', 2, '4743RF Panel Build Com', 1, 0),
  ('TMJ890', '4743RF', 3, '4743RF Field Wire Compl', 0, 1),
  ('TMJ890', '4743RF', 4, '4743RF Final Documentat', 0, 1),
  ('TMJ891', '4743LF', 0, '4743LF Initial PO', 1, 0),
  ('TMJ891', '4743LF', 1, '4743LF Engineering Com', 1, 0),
  ('TMJ891', '4743LF', 2, '4743LF Panel Build Comp', 1, 0),
  ('TMJ891', '4743LF', 3, '4743LF Field Wire Compl', 0, 1),
  ('TMJ891', '4743LF', 4, '4743LF Final Documentati', 0, 1),
  ('TMJ892', '2076', 0, '2076 Initial PO', 1, 0),
  ('TMJ892', '2076', 1, '2076 Engineering Comple', 1, 0),
  ('TMJ892', '2076', 2, '2743F Panel Build Compl', 1, 0),
  ('TMJ892', '2076', 3, '2076 Field Wire Complete', 1, 0),
  ('TMJ892', '2076', 4, '2076 Final Documentation', 0, 1),
  ('TMJ901', '4763', 0, '4763 Initial PO', 1, 0),
  ('TMJ901', '4763', 1, '4763 Engineering Comple', 0, 1),
  ('TMJ901', '4763', 2, '4763 Panel Build Complet', 0, 1),
  ('TMJ901', '4763', 3, '4763 Field Wire Complete', 0, 1),
  ('TMJ901', '4763', 4, '4763 Final Documentation', 0, 1),
  ('TMJ902', '4764', 0, '4764 Initial PO', 1, 0),
  ('TMJ902', '4764', 1, '4764 Engineering Comple', 0, 1),
  ('TMJ902', '4764', 2, '4764 Panel Build Complet', 0, 1),
  ('TMJ902', '4764', 3, '4764 Field Wire Complete', 0, 1),
  ('TMJ902', '4764', 4, '4764 Final Documentation', 0, 1),
  ('TMJ903', '4766', 0, '4766 Initial PO', 1, 0),
  ('TMJ903', '4766', 1, '4766 Engineering Comple', 0, 1),
  ('TMJ903', '4766', 2, '4766 Panel Build Complet', 0, 1),
  ('TMJ903', '4766', 3, '4766 Field Wire Complete', 0, 1),
  ('TMJ903', '4766', 4, '4766 Final Documentation', 0, 1),
  ('TMJ904', '4768', 0, '4768 Initial PO', 1, 0),
  ('TMJ904', '4768', 1, '4768 Engineering Comple', 0, 1),
  ('TMJ904', '4768', 2, '4768 Panel Build Complet', 0, 1),
  ('TMJ904', '4768', 3, '4768 Field Wire Complete', 0, 1),
  ('TMJ904', '4768', 4, '4768 Final Documentation', 0, 1),
  ('TMJ905', '4771', 0, '4771 Initial PO', 1, 0),
  ('TMJ905', '4771', 1, '4771 Engineering Comple', 0, 1),
  ('TMJ905', '4771', 2, '4771 Panel Build Complet', 0, 1),
  ('TMJ905', '4771', 3, '4771 Field Wire Complete', 0, 1),
  ('TMJ905', '4771', 4, '4771 Final Documentation', 0, 1),
  ('TMJ906', '4775', 0, '4775 Initial PO', 1, 0),
  ('TMJ906', '4775', 1, '4775 Engineering Comple', 0, 1),
  ('TMJ906', '4775', 2, '4775 Panel Build Complet', 0, 1),
  ('TMJ906', '4775', 3, '4775 Field Wire Complete', 0, 1),
  ('TMJ906', '4775', 4, '4775 Final Documentation', 0, 1),
  ('TMJ907', '4784', 0, '4784 Initial PO', 1, 0),
  ('TMJ907', '4784', 1, '4784 Engineering Comple', 0, 1),
  ('TMJ907', '4784', 2, '4784 Panel Build Complet', 0, 1),
  ('TMJ907', '4784', 3, '4784 Field Wire Complete', 0, 1),
  ('TMJ907', '4784', 4, '4784 Final Documentation', 0, 1),
  ('TMJ908', '4792', 0, '4792 Initial PO', 1, 0),
  ('TMJ908', '4792', 1, '4792 Engineering Comple', 0, 1),
  ('TMJ908', '4792', 2, '4792 Panel Build Complet', 0, 1),
  ('TMJ908', '4792', 3, '4792 Field Wire Complete', 0, 1),
  ('TMJ908', '4792', 4, '4792 Final Documentation', 0, 1),
  ('TMJ909', '4797', 0, '4797 Initial PO', 1, 0),
  ('TMJ909', '4797', 1, '4797 Engineering Comple', 0, 1),
  ('TMJ909', '4797', 2, '4797 Panel Build Complet', 0, 1),
  ('TMJ909', '4797', 3, '4797 Field Wire Complete', 0, 1),
  ('TMJ909', '4797', 4, '4797 Final Documentation', 0, 1),
  ('TMJ910', '4799', 0, '4799 Initial PO', 1, 0),
  ('TMJ910', '4799', 1, '4799 Engineering Comple', 0, 1),
  ('TMJ910', '4799', 2, '4799 Panel Build Complet', 0, 1),
  ('TMJ910', '4799', 3, '4799 Field Wire Complete', 0, 1),
  ('TMJ910', '4799', 4, '4799 Final Documentation', 0, 1),
  ('TMJ911', '4801', 0, '4801 Initial PO', 1, 0),
  ('TMJ911', '4801', 1, '4801 Engineering Comple', 0, 1),
  ('TMJ911', '4801', 2, '4801 Panel Build Complet', 0, 1),
  ('TMJ911', '4801', 3, '4801 Field Wire Complete', 0, 1),
  ('TMJ911', '4801', 4, '4801 Final Documentation', 0, 1),
  ('TMJ912', '4802', 0, '4802 Initial PO', 1, 0),
  ('TMJ912', '4802', 1, '4802 Engineering Comple', 0, 1),
  ('TMJ912', '4802', 2, '4802 Panel Build Complet', 0, 1),
  ('TMJ912', '4802', 3, '4802 Field Wire Complete', 0, 1),
  ('TMJ912', '4802', 4, '4802 Final Documentation', 0, 1)
),
-- Ledger's lines for the sales orders on the report, with their position.
so_lines as (
  select li.id, li.sales_order_id, s.number as so_number, li.description, li.invoiced, li.closed, li.invoice_id,
         row_number() over (partition by li.sales_order_id order by li.sort, li.created_at) - 1 as pos
  from sales_order_line_items li
  join sales_orders s on s.id = li.sales_order_id
  where s.number in (select so_number from report)
),
-- 1. Match each report line to a Ledger line: shortened description as a
--    prefix of the full one (position breaks a tie), else the same position.
by_text as (
  select distinct on (r.so_number, r.pos) r.so_number, r.pos, l.id as line_id
  from report r
  join so_lines l on l.so_number = r.so_number
   and regexp_replace(lower(coalesce(l.description, '')), '[^a-z0-9]', '', 'g') like regexp_replace(lower(coalesce(r.line_desc, '')), '[^a-z0-9]', '', 'g') || '%'
  order by r.so_number, r.pos, (l.pos = r.pos) desc, l.pos
),
by_pos as (
  select r.so_number, r.pos, l.id as line_id
  from report r
  join so_lines l on l.so_number = r.so_number and l.pos = r.pos
  where not exists (select 1 from by_text t where t.so_number = r.so_number and t.pos = r.pos)
    and not exists (select 1 from by_text t where t.line_id = l.id)
),
matched as (
  select r.so_number, r.po_number, r.pos, r.line_desc, r.shipped, r.remaining,
         l.id as line_id, l.sales_order_id, l.description,
         l.invoiced as was_invoiced, l.closed as was_closed, l.invoice_id as old_invoice_id
  from report r
  left join (select * from by_text union all select * from by_pos) x on x.so_number = r.so_number and x.pos = r.pos
  left join so_lines l on l.id = x.line_id
),
-- 2. The Ledger invoice that billed a shipped line: same sales order, same
--    line text, earliest wins.
inv_match as (
  select distinct on (m.line_id) m.line_id, i.id as invoice_id, i.number as invoice_number
  from matched m
  join invoices i on i.sales_order_id = m.sales_order_id
  join invoice_line_items il on il.invoice_id = i.id
   and regexp_replace(lower(coalesce(il.description, '')), '[^a-z0-9]', '', 'g') = regexp_replace(lower(coalesce(m.description, '')), '[^a-z0-9]', '', 'g')
  where m.line_id is not null and m.shipped > 0
  order by m.line_id, i.date, i.created_at
),
-- 3. What every line becomes: shipped -> invoiced + linked, remaining -> open.
plan as (
  select m.*, im.invoice_number,
         (m.line_id is not null and (m.shipped > 0 or m.remaining > 0)) as act,
         (m.shipped > 0) as new_invoiced,
         false as new_closed,
         case when m.shipped > 0 then coalesce(im.invoice_id, m.old_invoice_id) end as new_invoice_id
  from matched m
  left join inv_match im on im.line_id = m.line_id
),
-- 4. Each sales order's lines after the change, and its status from them.
new_state as (
  select l.id, l.sales_order_id, l.so_number,
         coalesce(p.new_invoiced, l.invoiced) as invoiced,
         coalesce(p.new_closed, l.closed) as closed,
         case when p.line_id is not null then p.new_invoice_id else l.invoice_id end as invoice_id
  from so_lines l
  left join plan p on p.line_id = l.id and p.act
),
so_agg as (
  select so_number, sales_order_id,
         count(*) filter (where not invoiced and not closed) as open_lines,
         max(invoice_id::text)::uuid as last_invoice
  from new_state group by so_number, sales_order_id
),
so_plan as (
  select s.id, s.number, s.po_number as old_po,
         case when coalesce(btrim(s.po_number), '') = '' then coalesce(nullif(r.po_number, ''), s.po_number) else s.po_number end as po_number,
         case when a.open_lines is null then s.status when a.open_lines = 0 then 'invoiced' else 'open' end as status,
         case when a.open_lines is null then s.invoice_id when a.open_lines = 0 then coalesce(s.invoice_id, a.last_invoice) end as invoice_id
  from sales_orders s
  join (select distinct so_number, po_number from report) r on r.so_number = s.number
  left join so_agg a on a.sales_order_id = s.id
),
-- 5. Apply.
upd_lines as (
  update sales_order_line_items li
  set invoiced = p.new_invoiced, closed = p.new_closed, invoice_id = p.new_invoice_id
  from plan p
  where li.id = p.line_id and p.act
  returning li.id
),
so_after as (
  update sales_orders s
  set po_number = sp.po_number, status = sp.status, invoice_id = sp.invoice_id
  from so_plan sp
  where s.id = sp.id
  returning s.number, s.po_number, s.status
)
-- 6. Review: one row per report line, what it was, what it is now.
select p.so_number, u.po_number, u.status as so_status, p.pos, p.line_desc as sage_line,
       case when p.shipped > 0 then 'invoiced' else 'open' end as sage_says,
       p.description as ledger_line,
       case when p.line_id is null then null when p.was_invoiced then 'invoiced' when p.was_closed then 'closed' else 'open' end as was,
       case when p.line_id is null then null when not p.act then 'unchanged' when p.new_invoiced then 'invoiced' when p.new_closed then 'closed' else 'open' end as now,
       p.invoice_number as linked_invoice,
       case
         when p.line_id is null then 'NO LEDGER LINE MATCHED'
         when p.shipped > 0 and p.new_invoice_id is null then 'invoiced in Sage, no Ledger invoice found'
         when p.shipped = 0 and p.old_invoice_id is not null then 'unlinked invoice ' || coalesce((select number from invoices where id = p.old_invoice_id), p.old_invoice_id::text)
         when p.was_closed and p.new_invoiced then 'was closed by hand: marked invoiced'
         when p.was_closed and p.act then 'reopened'
         when not p.was_invoiced and p.new_invoiced then 'marked invoiced'
         else ''
       end as note
from plan p
left join so_after u on u.number = p.so_number
order by p.so_number, p.pos;
