#!/usr/bin/env python3
"""sage-lists-sql.py — turn the Sage Vendor List (.xlsx) and Customer List (.pdf)
into a SQL data fix that fills each contact's posting account.

    python3 tools/sage-lists-sql.py "Import/Vendor List.xlsx" "Import/Customer List 09272026.pdf" \
        > app/supabase/data-fixes/2026-09-27_contact_accounts.sql

The SQL (run in the Supabase SQL editor, after migration 024):
  * fills a vendor's expense account, 1099 type, tax id and vendor id from the
    Vendor List, matched on the vendor's name (case, spaces and punctuation
    ignored) — an account or id already entered is left alone, the 1099 type
    and expense account are set from the list
  * sets every customer's sales account from the Customer List the same way
  * lists the vendors and customers on file that the lists did not name, so
    they can be set by hand under Vendors / Customers

Each statement stands on its own (no temp tables), so the editor's one
connection per statement is fine. The org is the first one on file — the
shop's own — because the editor runs as the postgres role, not a user.
"""
import re
import sys
import zipfile
import xml.etree.ElementTree as ET


def norm(s):
    return re.sub(r"[^a-z0-9]", "", str(s or "").lower())


def q(s):
    return "'" + str(s if s is not None else "").replace("'", "''") + "'"


def read_xlsx(path):
    z = zipfile.ZipFile(path)
    ns = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
    shared = []
    if "xl/sharedStrings.xml" in z.namelist():
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", ns):
            shared.append("".join(t.text or "" for t in si.iter("{%s}t" % ns["m"])))
    sheet = [n for n in z.namelist() if n.startswith("xl/worksheets/sheet")][0]
    rows = []
    for row in ET.fromstring(z.read(sheet)).iter("{%s}row" % ns["m"]):
        cells = {}
        for c in row.findall("m:c", ns):
            v = c.find("m:v", ns)
            col = re.sub(r"[0-9]", "", c.get("r"))
            cells[col] = "" if v is None else (shared[int(v.text)] if c.get("t") == "s" else v.text)
        rows.append(cells)
    head = {v.strip().lower(): k for k, v in rows[0].items()}
    out = []
    for r in rows[1:]:
        get = lambda name: (r.get(head.get(name, ""), "") or "").strip()
        if not get("vendor"):
            continue
        out.append({
            "id": get("vendor id"), "name": get("vendor"), "acct": get("expense accnt"),
            "tax": get("tax id no"), "ten99": get("1099 type"),
        })
    return out


def read_customers_pdf(path):
    try:
        import pdfplumber
    except ImportError:
        sys.exit("pdfplumber is required for the customer list: pip install pdfplumber")
    out = []
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            words = page.extract_words(x_tolerance=2, y_tolerance=3)
            rows = {}
            for w in words:
                rows.setdefault(round(w["top"] / 4), []).append(w)
            # The heading row fixes the columns: Customer ID | Customer | Bill To
            # Contact | Telephone 1 | ... | Sales Acct. Names are sliced by x, so a
            # contact name in the next column never rides along.
            x_name = x_contact = None
            for key in sorted(rows):
                ws = sorted(rows[key], key=lambda w: w["x0"])
                texts = [w["text"] for w in ws]
                if "Customer" in texts and "Bill" in texts and x_name is None:
                    cols = [w for w in ws if w["text"] == "Customer"]
                    x_name = cols[-1]["x0"]
                    x_contact = next(w["x0"] for w in ws if w["text"] == "Bill")
                    continue
                if x_name is None or not re.match(r"^\d{4}$", texts[-1]):
                    continue
                cid = " ".join(w["text"] for w in ws if w["x0"] < x_name - 2)
                name = " ".join(w["text"] for w in ws if x_name - 2 <= w["x0"] < x_contact - 2)
                if cid and name:
                    out.append({"id": cid, "name": name, "acct": texts[-1]})
    return out


def emit(vendors, customers, src):
    p = print
    p(f"-- Contact posting accounts from the Sage lists: {src}")
    p("-- Generated by tools/sage-lists-sql.py. Run in the Supabase SQL editor AFTER migration 024.")
    p("-- The org is the first on file (the shop's own); the editor runs as postgres, not a user.")
    p("")
    p("-- 1. Vendors: expense account, 1099 type, and tax id / vendor id where blank.")
    p("update contacts c set")
    p("  expense_account = v.acct,")
    p("  ten99 = v.ten99,")
    p("  tax_id = case when coalesce(btrim(c.tax_id), '') = '' then v.tax else c.tax_id end,")
    p("  code   = case when coalesce(btrim(c.code), '') = '' then v.vid else c.code end")
    p("from (values")
    vals = []
    for v in vendors:
        t = {"misc": "misc", "nec": "nec"}.get(v["ten99"].strip().lower(), "")
        vals.append(f"  ({q(norm(v['name']))}, {q(v['acct'])}, {q(t)}, {q(v['tax'])}, {q(v['id'])})")
    p(",\n".join(vals))
    p(") as v(name_key, acct, ten99, tax, vid)")
    p("where c.type = 'vendor'")
    p("  and c.org_id = (select id from orgs order by created_at limit 1)")
    p("  and regexp_replace(lower(c.name), '[^a-z0-9]', '', 'g') = v.name_key;")
    p("")
    p("-- 2. Customers: sales account.")
    p("update contacts c set sales_account = v.acct")
    p("from (values")
    seen = {}
    for cst in customers:                       # one row per name: the same customer can be listed twice
        seen.setdefault(norm(cst["name"]), cst["acct"])
    p(",\n".join(f"  ({q(k)}, {q(a)})" for k, a in seen.items()))
    p(") as v(name_key, acct)")
    p("where c.type = 'customer'")
    p("  and c.org_id = (select id from orgs order by created_at limit 1)")
    p("  and regexp_replace(lower(c.name), '[^a-z0-9]', '', 'g') = v.name_key;")
    p("")
    p("-- 3. Review: contacts the lists did not name (set their account by hand).")
    p("select type, name, coalesce(nullif(sales_account, ''), nullif(expense_account, ''), '(none)') as account")
    p("from contacts")
    p("where org_id = (select id from orgs order by created_at limit 1)")
    p("  and ((type = 'vendor' and coalesce(expense_account, '') = '') or (type = 'customer' and coalesce(sales_account, '') = ''))")
    p("order by type, name;")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    vendors = read_xlsx(sys.argv[1])
    customers = read_customers_pdf(sys.argv[2])
    sys.stderr.write(f"{len(vendors)} vendors, {len(customers)} customers\n")
    emit(vendors, customers, ", ".join(a.split("/")[-1] for a in sys.argv[1:]))
