#!/usr/bin/env python3
"""so-report-sql.py — turn a Sage "Sales Order Report" PDF into a SQL data fix.

    python3 tools/so-report-sql.py "Import/Sales Order Report 09122026.pdf" > fix.sql

Needs pdfplumber (`pip install pdfplumber`). The PDF is the Sage report printed
"by Sales Order Number, with shortened descriptions": one block per open sales
order, one line per item with Qty Ordered / Qty Shipped / Qty Remaining.

The SQL it prints (run in the Supabase SQL editor, see app/supabase/data-fixes/)
brings Ledger's sales orders into line with Sage, which is the book of record:

  * a blank PO number is filled from the job number that prefixes every line
    ("4763 Initial PO" -> PO 4763); a PO already entered is left alone
  * a line Sage has shipped is marked invoiced and linked to the Ledger
    invoice that billed it (matched on the invoice's sales order + line text)
  * a line Sage still has remaining is reopened — invoiced off, closed off —
    so it shows as available to bill again
  * the sales order's status is recomputed from its lines

Report lines are matched to Ledger lines by the shortened description as a
prefix of the full one, falling back to line position when the text differs.
The script ends with a SELECT that lists every line, what changed, and any
line it could not match, so the result is reviewable before COMMIT.
"""
import re
import sys

try:
    import pdfplumber
except ImportError:
    sys.exit("pdfplumber is required: pip install pdfplumber")

SO_RE = re.compile(r"^TMJ\d+$")
NUM_RE = re.compile(r"^\d+\.\d\d$")
DATE_RE = re.compile(r"^\d{1,2}/\d{1,2}/\d{2,4}$")
QTY_X = 390       # the three quantity columns sit to the right of this
HEADER_Y = 110    # page header (title, filter line, column headings) ends above this
DESC_X0, DESC_X1 = 250, 390   # Item ID / Line Description column


def read_report(path):
    """Yield (so_number, [(desc, ordered, shipped, remaining), ...]) per SO."""
    orders, current, pending = [], None, None
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            words = page.extract_words(x_tolerance=2, y_tolerance=3)
            rows = {}
            for w in words:
                if w["top"] < HEADER_Y:
                    continue
                rows.setdefault(round(w["top"] / 4), []).append(w)
            for key in sorted(rows):
                ws = sorted(rows[key], key=lambda w: w["x0"])
                texts = [w["text"] for w in ws]
                so = next((t for t in texts if SO_RE.match(t)), None)
                if so:
                    current = {"number": so, "lines": []}
                    orders.append(current)
                qty = [float(w["text"]) for w in ws if NUM_RE.match(w["text"]) and w["x0"] > QTY_X]
                if len(qty) == 3:
                    pending = qty
                desc = " ".join(w["text"] for w in ws
                                if DESC_X0 <= w["x0"] < DESC_X1 and not NUM_RE.match(w["text"]))
                if desc and current is not None and pending is not None:
                    current["lines"].append((desc, *pending))
                    pending = None
    return orders


def po_of(lines):
    """The job / PO number is the first token of the first line ("4724-F1 Initial PO")."""
    first = lines[0][0] if lines else ""
    return first.split()[0].rstrip("-") if first else ""


def q(s):
    return "'" + s.replace("'", "''") + "'"


def emit(orders, source):
    out = []
    p = out.append
    p(f"-- Sales-order reconciliation generated from: {source}")
    p("-- Generated by tools/so-report-sql.py. Run in the Supabase SQL editor.")
    p("-- Sage is the book of record: PO numbers, invoiced/open lines and SO status")
    p("-- below are brought into line with the report. Change the final COMMIT to")
    p("-- ROLLBACK to dry-run; the closing SELECT shows what would change either way.")
    p("begin;")
    p("")
    p("create temp table so_report (so_number text, po_number text, pos int, line_desc text, shipped numeric, remaining numeric) on commit drop;")
    p("insert into so_report (so_number, po_number, pos, line_desc, shipped, remaining) values")
    vals = []
    for o in orders:
        po = po_of(o["lines"])
        for i, (desc, ordered, shipped, remaining) in enumerate(o["lines"]):
            vals.append(f"  ({q(o['number'])}, {q(po)}, {i}, {q(desc)}, {shipped:g}, {remaining:g})")
    p(",\n".join(vals) + ";")
    p("")
    p(r"""-- text normaliser: case-, space- and punctuation-insensitive
create or replace function pg_temp.norm(t text) returns text language sql immutable as
$$ select regexp_replace(lower(coalesce(t, '')), '[^a-z0-9]', '', 'g') $$;

-- Ledger's lines for the sales orders on the report, with their position.
create temp table so_lines on commit drop as
select li.id, li.sales_order_id, s.number as so_number, li.description, li.invoiced, li.closed, li.invoice_id,
       row_number() over (partition by li.sales_order_id order by li.sort, li.created_at) - 1 as pos
from sales_order_line_items li
join sales_orders s on s.id = li.sales_order_id
where s.number in (select distinct so_number from so_report);

-- 1. Match each report line to a Ledger line: shortened description as a
--    prefix of the full one (position breaks a tie), else the same position.
create temp table so_match on commit drop as
select distinct on (r.so_number, r.pos)
       r.so_number, r.pos, r.line_desc, r.shipped, r.remaining, l.id as line_id, l.sales_order_id, l.description,
       l.invoiced as was_invoiced, l.closed as was_closed, l.invoice_id as old_invoice_id
from so_report r
left join so_lines l on l.so_number = r.so_number
  and pg_temp.norm(l.description) like pg_temp.norm(r.line_desc) || '%'
order by r.so_number, r.pos, (l.pos = r.pos) desc, l.pos;

update so_match m set line_id = l.id, sales_order_id = l.sales_order_id, description = l.description,
       was_invoiced = l.invoiced, was_closed = l.closed, old_invoice_id = l.invoice_id
from so_lines l
where m.line_id is null and l.so_number = m.so_number and l.pos = m.pos
  and l.id not in (select line_id from so_match where line_id is not null);

-- 2. Fill a blank PO number from the job number on the report.
update sales_orders s set po_number = r.po_number
from (select distinct so_number, po_number from so_report where po_number <> '') r
where s.number = r.so_number and coalesce(btrim(s.po_number), '') = '';

-- 3. Lines Sage has shipped: invoiced, not closed, linked to the invoice that
--    billed them (same sales order, same line text; earliest wins).
create temp table inv_match on commit drop as
select distinct on (m.line_id) m.line_id, i.id as invoice_id, i.number as invoice_number
from so_match m
join invoices i on i.sales_order_id = m.sales_order_id
join invoice_line_items il on il.invoice_id = i.id and pg_temp.norm(il.description) = pg_temp.norm(m.description)
where m.line_id is not null and m.shipped > 0
order by m.line_id, i.date, i.created_at;

update sales_order_line_items li
set invoiced = true, closed = false, invoice_id = coalesce(im.invoice_id, li.invoice_id)
from so_match m left join inv_match im on im.line_id = m.line_id
where li.id = m.line_id and m.shipped > 0;

-- 4. Lines Sage still has remaining: open again, so they are available to bill.
update sales_order_line_items li
set invoiced = false, closed = false, invoice_id = null
from so_match m
where li.id = m.line_id and m.shipped = 0 and m.remaining > 0;

-- 5. Recompute each sales order's status from its lines.
update sales_orders s
set status = case when agg.open_lines = 0 then 'invoiced' else 'open' end,
    invoice_id = case when agg.open_lines = 0 then coalesce(s.invoice_id, agg.last_invoice) else null end
from (
  select li.sales_order_id,
         count(*) filter (where not li.invoiced and not li.closed) as open_lines,
         max(li.invoice_id::text)::uuid as last_invoice
  from sales_order_line_items li
  where li.sales_order_id in (select distinct sales_order_id from so_lines)
  group by li.sales_order_id
) agg
where s.id = agg.sales_order_id;

-- 6. Review: one row per report line, what it was, what it is now.
select m.so_number, s.po_number, s.status as so_status, m.pos, m.line_desc as sage_line,
       case when m.shipped > 0 then 'invoiced' else 'open' end as sage_says,
       m.description as ledger_line,
       (case when m.was_invoiced then 'invoiced' when m.was_closed then 'closed' else 'open' end) as was,
       (case when li.invoiced then 'invoiced' when li.closed then 'closed' else 'open' end) as now,
       im.invoice_number as linked_invoice,
       case
         when m.line_id is null then 'NO LEDGER LINE MATCHED'
         when m.shipped > 0 and li.invoice_id is null then 'invoiced in Sage, no Ledger invoice found'
         when m.shipped = 0 and m.old_invoice_id is not null then 'unlinked invoice ' || coalesce((select number from invoices where id = m.old_invoice_id), m.old_invoice_id::text)
         when m.was_closed and li.invoiced then 'was closed by hand: marked invoiced'
         when m.was_closed and not li.closed then 'reopened'
         when not m.was_invoiced and li.invoiced then 'marked invoiced'
         else ''
       end as note
from so_match m
left join sales_orders s on s.number = m.so_number
left join sales_order_line_items li on li.id = m.line_id
left join inv_match im on im.line_id = m.line_id
order by m.so_number, m.pos;

commit;""")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    orders = read_report(sys.argv[1])
    if not orders:
        sys.exit("no sales orders found in the report")
    bad = [o["number"] for o in orders if not o["lines"]]
    if bad:
        sys.exit(f"no lines parsed for {', '.join(bad)}")
    sys.stderr.write(f"{len(orders)} sales orders, {sum(len(o['lines']) for o in orders)} lines\n")
    sys.stdout.write(emit(orders, sys.argv[1].split('/')[-1]))
