#!/usr/bin/env python3
"""so-report-sql.py — turn a Sage "Sales Order Report" PDF into a SQL data fix.

    python3 tools/so-report-sql.py "Import/Sales Order Report 09122026.pdf" > apply.sql
    python3 tools/so-report-sql.py --preview "Import/Sales Order Report 09122026.pdf" > preview.sql

Needs pdfplumber (`pip install pdfplumber`). The PDF is the Sage report printed
"by Sales Order Number, with shortened descriptions": one block per open sales
order, one line per item with Qty Ordered / Qty Shipped / Qty Remaining.

The SQL it prints (run in the Supabase SQL editor, see app/supabase/data-fixes/)
brings Ledger's sales orders into line with Sage, which is the book of record:

  * a blank PO number is filled from the job number that prefixes every line
    ("4763 Initial PO" -> PO 4763); a PO already entered is left alone
  * a line Sage has shipped is marked invoiced and linked to the Ledger
    invoice that billed it (matched on the invoice's sales order + line text)
  * a line Sage still has remaining is reopened — invoiced off, closed off —
    so it shows as available to bill again
  * the sales order's status is recomputed from its lines

Report lines are matched to Ledger lines by the shortened description as a
prefix of the full one, falling back to line position when the text differs.

The output is ONE SQL statement (a WITH chain), so it runs atomically anywhere —
the Supabase SQL editor runs each statement on its own connection, which is why
temp tables and BEGIN/COMMIT cannot be relied on there. It returns one row per
report line: what it was, what it is now, and a note for anything odd.
--preview emits the same statement without the UPDATEs, so you can see exactly
what would change first.
"""
import re
import sys

try:
    import pdfplumber
except ImportError:
    sys.exit("pdfplumber is required: pip install pdfplumber")

SO_RE = re.compile(r"^TMJ\d+$")
NUM_RE = re.compile(r"^\d+\.\d\d$")
DATE_RE = re.compile(r"^\d{1,2}/\d{1,2}/\d{2,4}$")
QTY_X = 390       # the three quantity columns sit to the right of this
HEADER_Y = 110    # page header (title, filter line, column headings) ends above this
DESC_X0, DESC_X1 = 250, 390   # Item ID / Line Description column


def read_report(path):
    """Yield (so_number, [(desc, ordered, shipped, remaining), ...]) per SO."""
    orders, current, pending = [], None, None
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            words = page.extract_words(x_tolerance=2, y_tolerance=3)
            rows = {}
            for w in words:
                if w["top"] < HEADER_Y:
                    continue
                rows.setdefault(round(w["top"] / 4), []).append(w)
            for key in sorted(rows):
                ws = sorted(rows[key], key=lambda w: w["x0"])
                texts = [w["text"] for w in ws]
                so = next((t for t in texts if SO_RE.match(t)), None)
                if so:
                    current = {"number": so, "lines": []}
                    orders.append(current)
                qty = [float(w["text"]) for w in ws if NUM_RE.match(w["text"]) and w["x0"] > QTY_X]
                if len(qty) == 3:
                    pending = qty
                desc = " ".join(w["text"] for w in ws
                                if DESC_X0 <= w["x0"] < DESC_X1 and not NUM_RE.match(w["text"]))
                if desc and current is not None and pending is not None:
                    current["lines"].append((desc, *pending))
                    pending = None
    return orders


def po_of(lines):
    """The job / PO number is the first token of the first line ("4724-F1 Initial PO")."""
    first = lines[0][0] if lines else ""
    return first.split()[0].rstrip("-") if first else ""


def q(s):
    return "'" + s.replace("'", "''") + "'"


NORM = "regexp_replace(lower(coalesce({}, '')), '[^a-z0-9]', '', 'g')"


def emit(orders, source, preview=False):
    norm = NORM.format
    out = []
    p = out.append
    p(f"-- Sales-order reconciliation generated from: {source}")
    p("-- Generated by tools/so-report-sql.py. Run in the Supabase SQL editor.")
    if preview:
        p("-- PREVIEW: reads only. Shows what the apply script would change.")
    else:
        p("-- Sage is the book of record: PO numbers, invoiced/open lines and SO status")
        p("-- are brought into line with the report. One statement, so it is all-or-nothing.")
    p("with report(so_number, po_number, pos, line_desc, shipped, remaining) as (values")
    vals = []
    for o in orders:
        po = po_of(o["lines"])
        for i, (desc, ordered, shipped, remaining) in enumerate(o["lines"]):
            vals.append(f"  ({q(o['number'])}, {q(po)}, {i}, {q(desc)}, {shipped:g}, {remaining:g})")
    p(",\n".join(vals))
    p("),")
    p(f"""-- Ledger's lines for the sales orders on the report, with their position.
so_lines as (
  select li.id, li.sales_order_id, s.number as so_number, li.description, li.invoiced, li.closed, li.invoice_id,
         row_number() over (partition by li.sales_order_id order by li.sort, li.created_at) - 1 as pos
  from sales_order_line_items li
  join sales_orders s on s.id = li.sales_order_id
  where s.number in (select so_number from report)
),
-- 1. Match each report line to a Ledger line: shortened description as a
--    prefix of the full one (position breaks a tie), else the same position.
by_text as (
  select distinct on (r.so_number, r.pos) r.so_number, r.pos, l.id as line_id
  from report r
  join so_lines l on l.so_number = r.so_number
   and {norm('l.description')} like {norm('r.line_desc')} || '%'
  order by r.so_number, r.pos, (l.pos = r.pos) desc, l.pos
),
by_pos as (
  select r.so_number, r.pos, l.id as line_id
  from report r
  join so_lines l on l.so_number = r.so_number and l.pos = r.pos
  where not exists (select 1 from by_text t where t.so_number = r.so_number and t.pos = r.pos)
    and not exists (select 1 from by_text t where t.line_id = l.id)
),
matched as (
  select r.so_number, r.po_number, r.pos, r.line_desc, r.shipped, r.remaining,
         l.id as line_id, l.sales_order_id, l.description,
         l.invoiced as was_invoiced, l.closed as was_closed, l.invoice_id as old_invoice_id
  from report r
  left join (select * from by_text union all select * from by_pos) x on x.so_number = r.so_number and x.pos = r.pos
  left join so_lines l on l.id = x.line_id
),
-- 2. The Ledger invoice that billed a shipped line: same sales order, same
--    line text, earliest wins.
inv_match as (
  select distinct on (m.line_id) m.line_id, i.id as invoice_id, i.number as invoice_number
  from matched m
  join invoices i on i.sales_order_id = m.sales_order_id
  join invoice_line_items il on il.invoice_id = i.id
   and {norm('il.description')} = {norm('m.description')}
  where m.line_id is not null and m.shipped > 0
  order by m.line_id, i.date, i.created_at
),
-- 3. What every line becomes: shipped -> invoiced + linked, remaining -> open.
plan as (
  select m.*, im.invoice_number,
         (m.line_id is not null and (m.shipped > 0 or m.remaining > 0)) as act,
         (m.shipped > 0) as new_invoiced,
         false as new_closed,
         case when m.shipped > 0 then coalesce(im.invoice_id, m.old_invoice_id) end as new_invoice_id
  from matched m
  left join inv_match im on im.line_id = m.line_id
),
-- 4. Each sales order's lines after the change, and its status from them.
new_state as (
  select l.id, l.sales_order_id, l.so_number,
         coalesce(p.new_invoiced, l.invoiced) as invoiced,
         coalesce(p.new_closed, l.closed) as closed,
         case when p.line_id is not null then p.new_invoice_id else l.invoice_id end as invoice_id
  from so_lines l
  left join plan p on p.line_id = l.id and p.act
),
so_agg as (
  select so_number, sales_order_id,
         count(*) filter (where not invoiced and not closed) as open_lines,
         max(invoice_id::text)::uuid as last_invoice
  from new_state group by so_number, sales_order_id
),
so_plan as (
  select s.id, s.number, s.po_number as old_po,
         case when coalesce(btrim(s.po_number), '') = '' then coalesce(nullif(r.po_number, ''), s.po_number) else s.po_number end as po_number,
         case when a.open_lines is null then s.status when a.open_lines = 0 then 'invoiced' else 'open' end as status,
         case when a.open_lines is null then s.invoice_id when a.open_lines = 0 then coalesce(s.invoice_id, a.last_invoice) end as invoice_id
  from sales_orders s
  join (select distinct so_number, po_number from report) r on r.so_number = s.number
  left join so_agg a on a.sales_order_id = s.id
),""")
    if preview:
        p("""so_after as (select number, po_number, status from so_plan)""")
    else:
        p("""-- 5. Apply.
upd_lines as (
  update sales_order_line_items li
  set invoiced = p.new_invoiced, closed = p.new_closed, invoice_id = p.new_invoice_id
  from plan p
  where li.id = p.line_id and p.act
  returning li.id
),
so_after as (
  update sales_orders s
  set po_number = sp.po_number, status = sp.status, invoice_id = sp.invoice_id
  from so_plan sp
  where s.id = sp.id
  returning s.number, s.po_number, s.status
)""")
    p(f"""-- 6. Review: one row per report line, what it was, what it is now.
select p.so_number, u.po_number, u.status as so_status, p.pos, p.line_desc as sage_line,
       case when p.shipped > 0 then 'invoiced' else 'open' end as sage_says,
       p.description as ledger_line,
       case when p.line_id is null then null when p.was_invoiced then 'invoiced' when p.was_closed then 'closed' else 'open' end as was,
       case when p.line_id is null then null when not p.act then 'unchanged' when p.new_invoiced then 'invoiced' when p.new_closed then 'closed' else 'open' end as now,
       p.invoice_number as linked_invoice,
       case
         when p.line_id is null then 'NO LEDGER LINE MATCHED'
         when p.shipped > 0 and p.new_invoice_id is null then 'invoiced in Sage, no Ledger invoice found'
         when p.shipped = 0 and p.old_invoice_id is not null then 'unlinked invoice ' || coalesce((select number from invoices where id = p.old_invoice_id), p.old_invoice_id::text)
         when p.was_closed and p.new_invoiced then 'was closed by hand: marked invoiced'
         when p.was_closed and p.act then 'reopened'
         when not p.was_invoiced and p.new_invoiced then 'marked invoiced'
         else ''
       end as note
from plan p
left join so_after u on u.number = p.so_number
order by p.so_number, p.pos;""")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a != "--preview"]
    preview = "--preview" in sys.argv[1:]
    if len(args) != 1:
        sys.exit(__doc__)
    orders = read_report(args[0])
    if not orders:
        sys.exit("no sales orders found in the report")
    bad = [o["number"] for o in orders if not o["lines"]]
    if bad:
        sys.exit(f"no lines parsed for {', '.join(bad)}")
    sys.stderr.write(f"{len(orders)} sales orders, {sum(len(o['lines']) for o in orders)} lines\n")
    sys.stdout.write(emit(orders, args[0].split('/')[-1], preview))
